version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: todo-list-mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "Str0ng!Pass@2025"
    volumes:
      - mssql_data:/var/opt/mssql
    restart: always

  mssql-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: todo-list-mssql-init
    depends_on:
      - mssql
    volumes:
      - ./docker/mssql/init:/scripts
    entrypoint: >
      sh -c "
      echo 'Aguardando SQL Server...';
      until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P 'Str0ng!Pass@2025' -C -Q 'SELECT 1' > /dev/null 2>&1; do
        sleep 2;
      done;
      echo 'SQL Server pronto. Criando database...';
      /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P 'Str0ng!Pass@2025' -C -i /scripts/01-create-database.sql;
      echo 'Database criada com sucesso.';
      "
    restart: "no"

volumes:
  mssql_data:
