
name: GCP CI/CD - Deploy API (PRODUÇÃO)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: todo-list-stefanini-gcp
      REGION: us-central1
      ARTIFACT_REPO_NAME: todo-list-repo
      IMAGE_NAME: todo-list-api

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Conceder permissão de execução ao gradlew
        run: chmod +x gradlew

      - name: Executar Testes
        run: ./gradlew clean test

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Docker para o Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Construir a Imagem Docker
        run: docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Enviar a Imagem para o Artifact Registry
        run: docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deployar no Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: todo-list-api-service
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

          env_vars: |
            SPRING_PROFILES_ACTIVE=gcp
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}