
name: GCP CI/CD - Deploy API (PRODUÇÃO)

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      ARTIFACT_REPO: ${{ secrets.ARTIFACT_REGISTRY }}
      SERVICE_NAME: todo-list-api-service
      IMAGE_NAME: todo-list-api

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Conceder permissão de execução ao gradlew
        run: chmod +x gradlew

      - name: Executar Testes
        run: ./gradlew clean test

      # === 1. AUTENTICAÇÃO NO GCP ===
      - name: Autenticar no Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # === 2. BUILD E PUSH PARA O ARTIFACT REGISTRY ===
      - name: Configurar Docker para o Artifact Registry
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Construir a Imagem Docker
        run: |
          docker build \
          --build-arg JAR_FILE=build/libs/todo-list-api-*.jar \
          --build-arg ACTIVE_PROFILE=gcp \
          -t ${ARTIFACT_REPO}/${IMAGE_NAME}:${{ github.sha }} .

      - name: Enviar a Imagem para o Artifact Registry
        run: docker push ${ARTIFACT_REPO}/${IMAGE_NAME}:${{ github.sha }}

      # === 3. DEPLOY PARA O CLOUD RUN ===
      - name: Deployar no Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.ARTIFACT_REPO }}/${IMAGE_NAME}:${{ github.sha }}
          env_vars: |
            SPRING_PROFILES_ACTIVE=gcp
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}